# Generated by Django 2.2.5 on 2022-01-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portflio_site',
            new_name='portfolio_site',
        ),
    ]
